### ISSUE TITLE
when will you release your code?

### ISSUE THREAD

**Issue by kzks001** [thuiar/Light-MILPopt#1]
We are working on MILP problem and we are quite interested in your work.

**Comment by HuigenYe** [comment]
Dear kzks001,

Thank you very much for your interest and kind words about our work!

We sincerely apologize for the delay in open-sourcing the code due to project collaboration reasons. We are happy to inform you that the full code has now been released, and we are conducting thorough testing and maintenance to ensure its robustness.

Please feel free to test it and reach out to us if you have any questions or feedback. We appreciate your patience and look forward to seeing how this work can contribute to further research.

Thanks again for your support and encouragement!

Best regards!
